language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: PHPCS=1 DEFAULT=0

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src "

notifications:
  email: false
